schema_version: 1.2.0
id: CVE-2021-39226
aliases:
- GHSA-69j6-29vr-p3j9
modified: 2021-11-28T23:22Z
published: 2021-10-05T18:15Z
details: 'Grafana is an open source data visualization platform. In affected versions
  unauthenticated and authenticated users are able to view the snapshot with the lowest
  database key by accessing the literal paths: /dashboard/snapshot/:key, or /api/snapshots/:key.
  If the snapshot "public_mode" configuration setting is set to true (vs default of
  false), unauthenticated users are able to delete the snapshot with the lowest database
  key by accessing the literal path: /api/snapshots-delete/:deleteKey. Regardless
  of the snapshot "public_mode" setting, authenticated users are able to delete the
  snapshot with the lowest database key by accessing the literal paths: /api/snapshots/:key,
  or /api/snapshots-delete/:deleteKey. The combination of deletion and viewing enables
  a complete walk through all snapshot data while resulting in complete snapshot data
  loss. This issue has been resolved in versions 8.1.6 and 7.5.11. If for some reason
  you cannot upgrade you can use a reverse proxy or similar to block access to the
  literal paths: /api/snapshots/:key, /api/snapshots-delete/:deleteKey, /dashboard/snapshot/:key,
  and /api/snapshots/:key. They have no normal function and can be disabled without
  side effects.'
severity:
- type: CVSS_V3
  score: 7.3
- type: CVSS_V2
  score: 6.8
affected:
- package:
    name: grafana
    cpe: cpe:2.3:a:grafana:grafana
- ranges:
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: 2d456a6375855364d098ede379438bf7f0667269
- database_specific:
    CWE:
    - CWE-287
    CVSS:
      Score: 7.3
      Severity: HIGH
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:L/A:L
references:
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/E6ANHRDBXQT6TURLP2THM26ZPDINFBEG/
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2021/10/05/4
- type: FIX
  url: https://github.com/grafana/grafana/commit/2d456a6375855364d098ede379438bf7f0667269
- type: WEB
  url: https://lists.fedoraproject.org/archives/list/package-announce@lists.fedoraproject.org/message/DCKBFUSY6V4VU5AQUYWKISREZX5NLQJT/
- type: ADVISORY
  url: https://github.com/grafana/grafana/security/advisories/GHSA-69j6-29vr-p3j9
- type: WEB
  url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-5-11/
- type: WEB
  url: https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-1-6/
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20211029-0008/
