schema_version: 1.2.0
id: CVE-2021-41174
aliases:
- GHSA-3j9m-hcv9-rpj8
modified: 2021-11-29T17:13Z
published: 2021-11-03T18:15Z
details: "Grafana is an open-source platform for monitoring and observability. In\
  \ affected versions if an attacker is able to convince a victim to visit a URL referencing\
  \ a vulnerable page, arbitrary JavaScript content may be executed within the context\
  \ of the victim's browser. The user visiting the malicious link must be unauthenticated\
  \ and the link must be for a page that contains the login button in the menu bar.\
  \ The url has to be crafted to exploit AngularJS rendering and contain the interpolation\
  \ binding for AngularJS expressions. AngularJS uses double curly braces for interpolation\
  \ binding: {{ }} ex: {{constructor.constructor(\u2018alert(1)\u2019)()}}. When the\
  \ user follows the link and the page renders, the login button will contain the\
  \ original link with a query parameter to force a redirect to the login page. The\
  \ URL is not validated and the AngularJS rendering engine will execute the JavaScript\
  \ expression contained in the URL. Users are advised to upgrade as soon as possible.\
  \ If for some reason you cannot upgrade, you can use a reverse proxy or similar\
  \ to block access to block the literal string {{ in the path."
severity:
- type: CVSS_V3
  score: 6.1
- type: CVSS_V2
  score: 4.3
affected:
- package:
    name: grafana
    cpe: cpe:2.3:a:grafana:grafana
- ranges:
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: fb85ed691290d211a5baa44d9a641ab137f0de88
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: 31b78d51c693d828720a5b285107a50e6024c912
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: 3cb5214fa45eb5a571fd70d6c6edf0d729983f82
- database_specific:
    CWE:
    - CWE-79
    CVSS:
      Score: 6.1
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N
references:
- type: FIX
  url: https://github.com/grafana/grafana/commit/fb85ed691290d211a5baa44d9a641ab137f0de88
- type: ADVISORY
  url: https://github.com/grafana/grafana/security/advisories/GHSA-3j9m-hcv9-rpj8
- type: FIX
  url: https://github.com/grafana/grafana/commit/31b78d51c693d828720a5b285107a50e6024c912
- type: FIX
  url: https://github.com/grafana/grafana/commit/3cb5214fa45eb5a571fd70d6c6edf0d729983f82
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20211125-0003/
