schema_version: 1.2.0
id: CVE-2021-43815
aliases:
- GHSA-7533-c8qv-jm9m
modified: 2022-01-10T14:10Z
published: 2021-12-10T21:15Z
details: Grafana is an open-source platform for monitoring and observability. Grafana
  prior to versions 8.3.2 and 7.5.12 has a directory traversal for arbitrary .csv
  files. It only affects instances that have the developer testing tool called TestData
  DB data source enabled and configured. The vulnerability is limited in scope, and
  only allows access to files with the extension .csv to authenticated users only.
  Grafana Cloud instances have not been affected by the vulnerability. Versions 8.3.2
  and 7.5.12 contain a patch for this issue. There is a workaround available for users
  who cannot upgrade. Running a reverse proxy in front of Grafana that normalizes
  the PATH of the request will mitigate the vulnerability. The proxy will have to
  also be able to handle url encoded paths.
severity:
- type: CVSS_V3
  score: 4.3
- type: CVSS_V2
  score: 3.5
affected:
- package:
    name: grafana
    cpe: cpe:2.3:a:grafana:grafana
- ranges:
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: d6ec6f8ad28f0212e584406730f939105ff6c6d3
  - type: GIT
    repo: https://github.com/grafana/grafana
    events:
    - introduced: '0'
    - fixed: fd48aee61e4328aae8d5303a9efd045fa0ca308d
- database_specific:
    CWE:
    - CWE-22
    CVSS:
      Score: 4.3
      Severity: MEDIUM
      Code: CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:U/C:L/I:N/A:N
references:
- type: FIX
  url: https://github.com/grafana/grafana/commit/d6ec6f8ad28f0212e584406730f939105ff6c6d3
- type: ADVISORY
  url: https://security.netapp.com/advisory/ntap-20220107-0006/
- type: FIX
  url: https://github.com/grafana/grafana/commit/fd48aee61e4328aae8d5303a9efd045fa0ca308d
- type: WEB
  url: https://github.com/grafana/grafana/releases/tag/v8.3.2
- type: ADVISORY
  url: https://github.com/grafana/grafana/security/advisories/GHSA-7533-c8qv-jm9m
- type: WEB
  url: http://www.openwall.com/lists/oss-security/2021/12/10/4
- type: WEB
  url: https://grafana.com/blog/2021/12/10/grafana-8.3.2-and-7.5.12-released-with-moderate-severity-security-fix/
