schema_version: 1.2.0
id: CVE-2020-15185
aliases:
- GHSA-jm56-5h66-w453
modified: 2020-10-02T15:23Z
published: 2020-09-17T22:15Z
details: In Helm before versions 2.16.11 and 3.3.2, a Helm repository can contain
  duplicates of the same chart, with the last one always used. If a repository is
  compromised, this lowers the level of access that an attacker needs to inject a
  bad chart into a repository. To perform this attack, an attacker must have write
  access to the index file (which can occur during a MITM attack on a non-SSL connection).
  This issue has been patched in Helm 3.3.2 and 2.16.11. A possible workaround is
  to manually review the index file in the Helm repository cache before installing
  software.
severity:
- type: CVSS_V3
  score: 2.7
- type: CVSS_V2
  score: 4.0
affected:
- package:
    name: helm
    cpe: cpe:2.3:a:helm:helm
- ranges:
  - type: GIT
    repo: https://github.com/helm/helm
    events:
    - introduced: '0'
    - fixed: 055dd41cbe53ce131ab0357524a7f6729e6e40dc
- database_specific:
    CWE:
    - CWE-74
    - CWE-694
    CVSS:
      Score: 2.7
      Severity: LOW
      Code: CVSS:3.1/AV:N/AC:L/PR:H/UI:N/S:U/C:N/I:L/A:N
references:
- type: ADVISORY
  url: https://github.com/helm/helm/security/advisories/GHSA-jm56-5h66-w453
- type: FIX
  url: https://github.com/helm/helm/commit/055dd41cbe53ce131ab0357524a7f6729e6e40dc
